modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]] #mandatory
modId = "tetrapak" #mandatory
version = "${file.jarVersion}" #mandatory
# A display name for the mod
displayName = "Tetra Pak" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tetra-pak"
logoFile = "tetrapak.png"
credits = "Thanks to Grimmauld and simibubi for helping with code and Mickelus for creating Tetra"
authors = "Noobulus, Grimmauld"
description = '''
Tetra Pak is an add-on mod for Tetra that introduces new materials with unique effects to Tetra.

Currently, only Create is supported. Check back soon for more!
'''
[[dependencies.tetrapak]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[39,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.tetrapak]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tetrapak]]
modId = "tetra"
mandatory = true
versionRange = "[3.8.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tetrapak]]
modId = "mgui"
mandatory = true
versionRange = "[3.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tetrapak]]
modId = "tetranomicon"
mandatory = false
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tetrapak]]
modId = "create"
mandatory = false
versionRange = "[mc1.16.3_v0.3.1b,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tetrapak]]
modId = "druidcraft"
mandatory = false
versionRange = "[0.4.52,)"
ordering = "NONE"
side = "BOTH"